# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f5c67d84be3a113964dd5cce45defd043d3046e4ba8e64b02f5a960a78b5ce75b67898ecd3ea1532f1d3b67f3512f1522a3f8f86cab0b953e6bad126d16e922

test:
  secret_key_base: 760d6b903a7eea56162f95922cdedfb2f0155dc9d6bd1ca8649702e42d15bfdd138db3a252817743db0064a31f9530e7e944cc53c6384f8bea1b0d7c10926a09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
